/**
 * Curated PT → EN UI translations. Machine translation (Google) routinely drops words,
 * mistranslates medical terms, and breaks "eletroterapia" / "Ver módulo" style phrases.
 * Keys are matched via normalizeLookupKey (lowercase, no diacritics).
 */

const stripDiacritics = (text: string) =>
  text.normalize("NFD").replace(/\p{Diacritic}/gu, "");

export const normalizeLookupKey = (text: string) =>
  stripDiacritics(
    text
      .split("\n")
      .map((line) => line.replace(/[ \t]+/g, " ").trim())
      .join("\n")
      .replace(/\n{3,}/g, "\n\n")
      .trim(),
  ).toLowerCase();

const PAIRS: readonly [string, string][] = [
  // Auth & nav
  ["Entrar", "Sign In"],
  ["Começar", "Sign Up"],
  ["Acessar", "Sign In"],
  ["Sobre", "About"],
  ["Sair", "Log Out"],
  ["Voltar", "Back"],
  ["Voltar para o início", "Back to home"],
  ["Perfil", "Profile"],
  ["Admin", "Admin"],
  ["Buscar", "Search"],
  ["Contato", "Contact"],
  ["Blog", "Blog"],
  ["Carregando...", "Loading..."],
  ["Carregando", "Loading"],

  // Dashboard
  ["Carregando seu painel...", "Loading your dashboard..."],
  ["Bem-vindo", "Welcome"],
  ["Aulas concluídas", "Lessons completed"],
  ["Cápsulas concluídas", "Capsules completed"],
  ["Módulos concluídos", "Modules completed"],
  ["Minutos aprendidos", "Minutes studied"],
  ["Em alta hoje", "Trending today"],
  ["Em Alta Hoje", "Trending today"],
  ["Módulos", "Modules"],
  ["Nenhum módulo disponível ainda.", "No modules available yet."],
  ["Nenhum módulo disponível ainda", "No modules available yet"],
  ["Progresso no ciclo", "Cycle progress"],
  ["Resumo rápido", "Quick summary"],
  ["Continuar de Onde Parou", "Continue where you left off"],
  ["Explorar Módulos", "Explore modules"],
  ["Nenhum Módulo Disponível Ainda", "No modules available yet"],
  ["Relatar um bug", "Report a bug"],
  ["Excluir conta", "Delete account"],
  ["O que você quer aprender hoje?", "What do you want to learn today?"],
  ["Abrir busca", "Open search"],
  ["de", "of"],
  ["módulos concluídos", "modules completed"],

  // Enrollment & actions
  ["Matricular", "Enroll"],
  ["Matricular-se", "Enroll"],
  ["Matrícula Necessária", "Enrollment required"],
  ["Você precisa se matricular neste módulo para acessar as aulas.", "You need to enroll in this module to access the lessons."],
  ["O módulo que você está procurando não existe ou foi removido.", "The module you are looking for does not exist or was removed."],
  ["aulas concluídas", "lessons completed"],
  ["Os laboratórios virtuais estarão disponíveis em breve.", "Virtual labs will be available soon."],
  ["As cápsulas para este módulo ainda estão sendo preparadas.", "Capsules for this module are still being prepared."],
  ["Concluída", "Completed"],
  ["Bloqueada", "Locked"],
  ["Ver Cápsulas", "View capsules"],
  ["Ver Aulas", "View lessons"],
  ["Refazer o Módulo", "Retake module"],
  ["Matriculado", "Enrolled"],
  ["Desmatricular", "Unenroll"],
  ["Matrícula necessária", "Enrollment required"],
  ["Matrícula realizada!", "Enrollment completed!"],
  ["Matrícula cancelada", "Enrollment canceled"],
  ["Refazer módulo", "Retake module"],
  ["Refazer", "Retake"],
  ["Iniciar", "Start"],
  ["Continuar", "Continue"],
  ["Concluir", "Complete"],
  ["Concluído", "Completed"],
  ["Concluída", "Completed"],
  ["Em Progresso", "In progress"],
  ["Em progresso", "In progress"],
  ["Ver cápsulas", "View capsules"],
  ["Conferir", "Check out"],
  ["Todas as cápsulas", "All capsules"],
  ["Cápsula Rápida", "Quick capsule"],
  ["Cápsula em Progresso", "Capsule in progress"],
  ["Cancelar Matrícula", "Cancel enrollment"],
  ["Cápsulas", "Capsules"],
  ["Aulas", "Lessons"],
  ["Seu painel de aprendizagem", "Your learning dashboard"],
  ["Ver aulas", "View lessons"],
  ["Ver módulo", "View module"],
  ["Ver módulos", "View modules"],
  ["Ver catálogo de cápsulas", "Browse all capsules"],
  ["Abrir conteúdo", "Open content"],
  ["Explorar tema", "Explore topic"],
  ["Encontrar conteúdo", "Find content"],

  // Modules / lessons / capsules
  ["Carregando módulo...", "Loading module..."],
  ["Carregando módulos...", "Loading modules..."],
  ["Módulo não encontrado", "Module not found"],
  ["Módulo", "Module"],
  ["Módulos", "Modules"],
  ["Progresso do Módulo", "Module progress"],
  ["Carregando aula...", "Loading lesson..."],
  ["Carregando aulas...", "Loading lessons..."],
  ["Aula", "Lesson"],
  ["Aulas", "Lessons"],
  ["Aula bloqueada", "Lesson locked"],
  ["Aula Completa", "Full lesson"],
  ["Aula não encontrada", "Lesson not found"],
  ["Carregando cápsula...", "Loading capsule..."],
  ["Carregando cápsulas...", "Loading capsules..."],
  ["Cápsula", "Capsule"],
  ["Cápsulas", "Capsules"],
  ["Cápsulas Rápidas", "Quick capsules"],
  ["Cápsula rápida", "Quick capsule"],
  ["cápsulas rápidas", "quick capsules"],
  ["capsulas rapidas", "quick capsules"],
  ["capsula rapida", "quick capsule"],
  ["Nenhuma Cápsula Disponível", "No capsules available"],
  ["Nenhuma cápsula disponível", "No capsules available"],
  ["Nenhum conteúdo disponível ainda", "No content available yet"],
  ["Nenhum conteúdo disponível ainda.", "No content available yet."],

  // Labs & charts
  ["Laboratório Virtual", "Virtual lab"],
  ["Laboratórios Virtuais", "Virtual labs"],
  ["Laboratório virtual", "Virtual lab"],
  ["Laboratórios virtuais", "Virtual labs"],
  ["Carregando laboratório...", "Loading lab..."],
  ["Carregando laboratórios...", "Loading labs..."],
  ["Carregando preview...", "Loading preview..."],
  ["Carregando viewer...", "Loading viewer..."],
  ["Carregando volume...", "Loading volume..."],
  ["Carregando gráfico...", "Loading chart..."],
  ["Carregando controles...", "Loading controls..."],
  ["Abrir laboratório AR", "Open AR lab"],
  ["Imagem médica · RA", "Medical imaging · AR"],
  ["Cortes anatômicos em RA", "Anatomical slices in AR"],
  ["Nenhum volume carregado", "No volume loaded"],
  ["Nenhum volume clínico carregado.", "No clinical volume loaded."],
  ["Nenhuma imagem disponível", "No image available"],
  ["Nenhum lab virtual", "No virtual lab"],
  ["Nenhum lab virtual publicado disponível.", "No published virtual lab available."],
  ["Nenhum gráfico publicado disponível.", "No published chart available."],
  ["Gráfico paramétrico", "Parametric chart"],
  ["Gráficos paramétricos", "Parametric charts"],

  // Search
  ["Carregando busca...", "Loading search..."],
  ["Buscar aulas, cápsulas ou módulos...", "Search lessons, capsules, or modules..."],
  ["Conteúdos sugeridos pela IA", "AI-suggested content"],
  ["Nenhum resultado de cápsulas para esta busca.", "No capsule results for this search."],
  ["Nenhum resultado de aulas para esta busca.", "No lesson results for this search."],
  ["Nenhum resultado de módulos para esta busca.", "No module results for this search."],

  // Discovery prompt
  ["O que você gostaria de aprender hoje?", "What would you like to learn today?"],
  ["Descubra o conteúdo ProGenia", "Discover ProGenia content"],
  ["Buscar conteúdos", "Search content"],
  ["Ou escolha um tema", "Or choose a topic"],
  ["Ou continue de onde parou", "Or continue where you left off"],

  // Medical / discipline terms
  ["Ultrassom", "Ultrasound"],
  ["Ultrassom diagnóstico", "Diagnostic ultrasound"],
  ["Ultrassom terapêutico", "Therapeutic ultrasound"],
  ["Eletroterapia", "Electrotherapy"],
  ["Fotobiomodulação", "Photobiomodulation"],
  ["Diagnóstico por imagem", "Medical imaging"],
  ["Diagnóstico por Imagem", "Medical Imaging"],
  ["Imagem médica", "Medical imaging"],
  ["Imagem por RM", "MRI imaging"],
  ["Imagem por RM (MRI)", "MRI imaging lab"],
  ["ressonância magnética", "magnetic resonance imaging"],
  ["Parâmetros e segurança", "Parameters and safety"],
  ["Parâmetros de estimulação", "Stimulation parameters"],
  ["Parâmetros de aplicação", "Application parameters"],
  ["Indicações clínicas", "Clinical indications"],
  ["Mecanismos biológicos", "Biological mechanisms"],
  ["Explorar tudo", "Explore all"],
  ["Laboratório virtual de eletroterapia", "Electrotherapy virtual lab"],
  ["Simulações práticas", "Practical simulations"],
  ["Equipamentos e protocolos", "Equipment and protocols"],
  ["Ver todos os labs", "See all labs"],

  // Gamification
  ["Conquistas", "Achievements"],
  ["Carregando conquistas...", "Loading achievements..."],
  ["Carregando ranking...", "Loading leaderboard..."],
  ["Nível", "Level"],
  ["Sequência", "Streak"],
  ["dias", "days"],
  ["Pontos", "Points"],
  ["Badges", "Badges"],
  ["Emblemas", "Badges"],

  // Profile & misc
  ["Salvar", "Save"],
  ["Cancelar", "Cancel"],
  ["Editar", "Edit"],
  ["Excluir", "Delete"],
  ["Confirmar", "Confirm"],
  ["Fechar", "Close"],
  ["Abrir", "Open"],
  ["Próximo", "Next"],
  ["Anterior", "Previous"],
  ["Progresso", "Progress"],
  ["Descrição", "Description"],
  ["Título", "Title"],
  ["Publicado", "Published"],
  ["Rascunho", "Draft"],
  ["Erro", "Error"],
  ["Sucesso", "Success"],
  ["Aviso", "Notice"],
  ["Informações", "Information"],
  ["Informações Anatômicas", "Anatomical information"],
  ["Fatia Atual", "Current slice"],
  ["Orientação", "Orientation"],
  ["Sequência", "Sequence"],
  ["Axial", "Axial"],

  // Blog
  ["Nenhum post disponível no momento.", "No posts available at the moment."],
  ["Todas as notícias", "All posts"],
  ["Conteúdos", "Insights"],

  // Common fragments (prevent bad MT when split across nodes)
  ["concluídas", "completed"],
  ["concluídos", "completed"],
  ["disponível", "available"],
  ["disponíveis", "available"],
  ["necessária", "required"],
  ["necessário", "required"],
  ["realizada", "completed"],
  ["realizado", "completed"],
  ["aprendidos", "studied"],
  ["explorar", "explore"],
  ["experimentar", "try"],
  ["matrícula", "enrollment"],
  ["matricular", "enroll"],
  ["painel", "dashboard"],
  ["trilha", "path"],
  ["laboratório", "lab"],
  ["laboratórios", "labs"],
  ["fundamentos", "fundamentals"],
  ["simulação", "simulation"],
  ["protocolos", "protocols"],
  ["parâmetros", "parameters"],
  ["indicações", "indications"],
  ["mecanismos", "mechanisms"],
  ["contéudo", "content"],
  ["contéudos", "content"],
  ["conteúdo", "content"],
  ["conteúdos", "content"],
  ["catálogo", "catalog"],
  ["catálogo de cápsulas", "capsule catalog"],
  ["questionário", "quiz"],
  ["questionários", "quizzes"],
  ["vídeo", "video"],
  ["vídeos", "videos"],
  ["imagem", "image"],
  ["imagens", "images"],
  ["texto", "text"],
  ["minutos", "minutes"],
  ["hora", "hour"],
  ["horas", "hours"],
  ["estudante", "student"],
  ["profissional", "professional"],
  ["fisioterapia", "physical therapy"],
  ["reabilitação", "rehabilitation"],
  ["clínico", "clinical"],
  ["clínica", "clinical"],
  ["educacional", "educational"],
  ["formação", "training"],
  ["prática", "practice"],
  ["segurança", "safety"],
  ["contraste", "contrast"],
  ["sequências", "sequences"],
  ["interpretação", "interpretation"],
  ["tomografia", "computed tomography"],
  ["fusão multimodal", "multimodal fusion"],
];

export const PT_EN_OVERRIDES: Record<string, string> = Object.fromEntries(
  PAIRS.map(([pt, en]) => [normalizeLookupKey(pt), en]),
);

/** Phrase glossary for substring replacement before machine translation (longest first). */
export const PT_EN_GLOSSARY_PHRASES: readonly { source: string; target: string }[] = [...PAIRS]
  .sort((a, b) => b[0].length - a[0].length)
  .map(([source, target]) => ({ source, target }));

export function getForcedPtEnOverride(text: string): string | undefined {
  const key = normalizeLookupKey(text);
  if (!key) return undefined;
  return PT_EN_OVERRIDES[key];
}
